INSERT INTO tb_user (username, email, job) VALUES ('Gary B. Coleman','bobcoleman@email.com', 'RH');
INSERT INTO tb_user (username, email, job) VALUES ('Whitney Houston','whithst@email.com', 'Desenvolvedor');
INSERT INTO tb_user (username, email, job) VALUES ('Lulu Santos','lulus@email.com', 'Contador');
INSERT INTO tb_user (username, email, job) VALUES ('Frank Ocean','franko@email.com', 'Publicitário');
INSERT INTO tb_user (username, email, job) VALUES ('Seu Jorge','jorge@email.com', 'Diretor');
INSERT INTO tb_user (username, email, job) VALUES ('Arnaldo Antunes','ants@email.com', 'RP');
INSERT INTO tb_user (username, email, job) VALUES ('Jon Bon Jovi','jovis@email.com', 'Advogado');
INSERT INTO tb_user (username, email, job) VALUES ('Arlindo Cruz','acruz@email.com', 'Diretor');
INSERT INTO tb_user (username, email, job) VALUES ('Kendrick Lamar','kelama@email.com', 'Operário');
INSERT INTO tb_user (username, email, job) VALUES ('Chico Buarque','chico@email.com', 'RP');
INSERT INTO tb_user (username, email, job) VALUES ('Chorão','bigcry@email.com', 'Desenvolvedor');
INSERT INTO tb_user (username, email, job) VALUES ('Childish Gambino','gambs@email.com', 'Desenvolvedor');
INSERT INTO tb_user (username, email, job) VALUES ('Michael Jackson','mj@email.com', 'Publicitário');
INSERT INTO tb_user (username, email, job) VALUES ('Bjork','bjorkn@email.com', 'Contador');
INSERT INTO tb_user (username, email, job) VALUES ('Mac Miller','milts@email.com', 'Advogado');
INSERT INTO tb_user (username, email, job) VALUES ('Nick Mulver','movie@email.com', 'Operário');
INSERT INTO tb_user (username, email, job) VALUES ('Eliott Smith','smiths@email.com', 'Operário');
INSERT INTO tb_user (username, email, job) VALUES ('Kid Abelha','abelhao@email.com', 'Operário');
INSERT INTO tb_user (username, email, job) VALUES ('Leci Brandão','brandale@email.com', 'Desenvolvedor');
INSERT INTO tb_user (username, email, job) VALUES ('Cartola','cartola@email.com', 'Operário');
INSERT INTO tb_user (username, email, job) VALUES ('Tom Jobim','jobs@email.com', 'Operário');